package report

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestGenerateUsesTF9FilenameAndBranding(t *testing.T) {
	runAt := time.Date(2026, time.June, 12, 3, 4, 5, 0, time.UTC)
	path, err := Generate(nil, Options{
		Command:   "plan",
		RunAt:     runAt,
		OutputDir: t.TempDir(),
	})
	if err != nil {
		t.Fatal(err)
	}
	if got, want := filepath.Base(path), "tf9-plan-20260612-030405.html"; got != want {
		t.Fatalf("report filename = %q, want %q", got, want)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !containsAll(string(data), "Generated by tf9", "tf9-color-mode") {
		t.Fatalf("generated report does not contain tf9 branding")
	}
}

func TestParseReportNameUsesTF9Prefix(t *testing.T) {
	cmd, runAt, live := ParseReportName("tf9-apply-20260612-030405.html")
	if cmd != "apply" || live || runAt.UTC().Format("20060102-150405") != "20260612-030405" {
		t.Fatalf("ParseReportName() = %q, %v, %v", cmd, runAt, live)
	}

	cmd, runAt, live = ParseReportName("tf9-plan-live.html")
	if cmd != "plan" || !live || !runAt.IsZero() {
		t.Fatalf("live ParseReportName() = %q, %v, %v", cmd, runAt, live)
	}
}

func containsAll(value string, needles ...string) bool {
	for _, needle := range needles {
		if !strings.Contains(value, needle) {
			return false
		}
	}
	return true
}
