package report

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestGenerateUsesTF9FilenameAndBranding(t *testing.T) {
	runAt := time.Date(2026, time.June, 12, 3, 4, 5, 0, time.UTC)
	path, err := Generate(nil, Options{
		Command:   "plan",
		RunAt:     runAt,
		OutputDir: t.TempDir(),
	})
	if err != nil {
		t.Fatal(err)
	}
	if got, want := filepath.Base(path), "tf9-plan-20260612-030405.html"; got != want {
		t.Fatalf("report filename = %q, want %q", got, want)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !containsAll(string(data), "Generated by tf9", "tf9-color-mode") {
		t.Fatalf("generated report does not contain tf9 branding")
	}
}

func TestGenerateShowsAppliedBoolean(t *testing.T) {
	path, err := Generate([]EnvResult{
		{Env: "dev", Profile: "test", Applied: true},
		{Env: "prod", Profile: "test", Applied: false, Failed: true},
	}, Options{
		Command:   "apply",
		RunAt:     time.Date(2026, time.June, 12, 3, 4, 5, 0, time.UTC),
		OutputDir: t.TempDir(),
	})
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	html := string(data)
	if !containsAll(html, "<th>Applied</th>", ">True</span>", ">False</span>") {
		t.Fatalf("generated report does not contain applied booleans")
	}
	if strings.Contains(html, "<th>Status</th>") {
		t.Fatalf("generated report still contains status column")
	}
}

func TestGenerateEmbedsTicketInHTMLAndSidecar(t *testing.T) {
	dir := t.TempDir()
	path, err := Generate(nil, Options{
		Command:   "plan",
		RunAt:     time.Date(2026, time.June, 12, 3, 4, 5, 0, time.UTC),
		OutputDir: dir,
		Ticket:    "OPS-42",
		TicketURL: "https://tickets.example/browse/OPS-42",
	})
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !containsAll(string(data), "Ticket:", "OPS-42", "https://tickets.example/browse/OPS-42") {
		t.Fatal("generated HTML does not contain ticket metadata")
	}
	sidecar, err := os.ReadFile(strings.TrimSuffix(path, ".html") + ".json")
	if err != nil {
		t.Fatal(err)
	}
	var sum Summary
	if err := json.Unmarshal(sidecar, &sum); err != nil {
		t.Fatal(err)
	}
	if sum.Ticket != "OPS-42" || sum.TicketURL != "https://tickets.example/browse/OPS-42" {
		t.Fatalf("ticket sidecar metadata = %#v", sum)
	}
}

func TestGenerateChangesTableSupportsSortingAndPersistentExpansion(t *testing.T) {
	output := `# terraform_data.updated will be updated in-place
~ resource "terraform_data" "updated" {
}
# terraform_data.created will be created
+ resource "terraform_data" "created" {
}`
	path, err := Generate([]EnvResult{
		{Env: "dev", Profile: "test", Change: 1, Add: 1, Output: output},
	}, Options{
		Command:   "plan",
		RunAt:     time.Date(2026, time.June, 12, 3, 4, 5, 0, time.UTC),
		OutputDir: t.TempDir(),
	})
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	html := string(data)
	if !containsAll(html,
		`onchange="sortRct(this)"`,
		`data-action="change"`,
		`data-action="add"`,
		`data-order="0"`,
		`function sortRct(select)`,
		`body.appendChild(block)`,
	) {
		t.Fatalf("generated report does not contain sortable persistent change rows")
	}
}

func TestParseReportNameUsesTF9Prefix(t *testing.T) {
	cmd, runAt, live := ParseReportName("tf9-apply-20260612-030405.html")
	if cmd != "apply" || live || runAt.UTC().Format("20060102-150405") != "20260612-030405" {
		t.Fatalf("ParseReportName() = %q, %v, %v", cmd, runAt, live)
	}

	cmd, runAt, live = ParseReportName("tf9-plan-live.html")
	if cmd != "plan" || !live || !runAt.IsZero() {
		t.Fatalf("live ParseReportName() = %q, %v, %v", cmd, runAt, live)
	}
}

func containsAll(value string, needles ...string) bool {
	for _, needle := range needles {
		if !strings.Contains(value, needle) {
			return false
		}
	}
	return true
}
