import { expect, test } from '@playwright/test';
import { openNewRunModal, pickCommand, selectOnlyTarget, shot } from './helpers';

// Reports are generated by real runs, so this spec seeds one plan run first
// (independent of test ordering) and then exercises the reports surfaces.
test('a plan run produces a report that opens in the viewer', async ({ page }) => {
  // ── Seed: run a plan so a report file exists ──
  const modal = await openNewRunModal(page);
  await pickCommand(page, 'plan');
  await modal.locator('.tile', { hasText: 'Promotion' }).click();
  await selectOnlyTarget(page, 'dev');
  await modal.getByRole('button', { name: /^Run plan$/ }).click();
  await expect(page.locator('.splitpanel .rstatus.success')).toBeVisible({ timeout: 45_000 });

  // ── Reports list ──
  await page.goto('/#reports');
  await expect(page.locator('.page-title', { hasText: 'Terraform Reports' })).toBeVisible();
  const card = page.locator('.rh-card').first();
  await expect(card).toBeVisible({ timeout: 15_000 });
  await expect(card.locator('.badge')).toContainText('plan');
  await shot(page, 'reports-cards');

  // ── List view toggle ──
  await page.locator('.rh-view-toggle button', { hasText: 'List' }).click();
  await expect(page.locator('table.rh-tbl')).toBeVisible();

  // ── Filters ──
  await page.locator('.rh-filter', { hasText: 'Plan' }).click();
  await expect(page.locator('table.rh-tbl tbody tr').first()).toBeVisible();

  // ── Open the report viewer ──
  await page.locator('.rh-view-toggle button', { hasText: 'Cards' }).click();
  await page.locator('.rh-card').first().click();
  await expect(page.locator('.report-viewer')).toBeVisible();
  await expect(page.getByRole('button', { name: /Back to Reports/ })).toBeVisible();
  await shot(page, 'report-viewer');
});
